routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Auth::routes();
//Route::resource('login','LoginController');
Route::middleware(['auth'])->group(function (){
    Route::resource('sub_module','SubModuleController');
    Route::get('generate/route','HomeController@generateRoute')->name('generate.route');
    Route::resource('company_structure','CompanyStructureController');
    Route::resource('job_detail','JobDetailController');
    Route::resource('overtime_management','OvertimeController');
    Route::resource('leave_management','LeaveManagementController');
    Route::resource('attendance','AttendanceController');
    Route::resource('users','UserController');
});
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/employees','EmployeeController');

app/Attendance.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Attendance extends Model
{
    //
}

app/CompanyStructure.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CompanyStructure extends Model
{
    //
    protected $fillable = [
        'name', 'description', 'address', 'type_id', 'parent_id'
    ];

    public function getTypeIdParent(){
        return $this->belongsTo('App\CompanyStructureType','type_id');
    }

    public function getParent(){
        return $this->belongsTo('App\CompanyStructure','parent_id');
    }

    public function getChildren(){
        return $this->hasMany('App\CompanyStructure','parent_id');
    }
}

app/CompanyStructureType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CompanyStructureType extends Model
{
    //
}

app/Department.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    //
    protected $fillable = [
        'department_name', 'department_motto', 'is_enabled',
    ];
}

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    //
}

app/EmployeeContact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EmployeeContact extends Model
{
    //
}

app/EmployeeEducation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EmployeeEducation extends Model
{
    //
}

app/EmployeeJobDescription.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EmployeeJobDescription extends Model
{
    //
}

app/EmployeeSocialMedia.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EmployeeSocialMedia extends Model
{
    //
}

app/EmployeeStatus.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EmployeeStatus extends Model
{
    //
}

app/EmployeeWorkExperience.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EmployeeWorkExperience extends Model
{
    //
}

app/GlobalModule.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;

class GlobalModule extends Model
{
    //
    protected $modules;
    protected $keyValuePair;

    public function __construct(Collection $modules)
    {
        $this->modules = $modules;
        foreach ($modules as $module){
            $this->keyValuePair[$module->key] = $module->value;
        }
    }

    public function has(string $key){ /* check key exists */ }
    public function contains(string $key){ /* check value exists */ }
    public function getModules(){
        return $this->modules;
    }
    public function get(string $key){
        return $this->modules[$key];
        /* get by key */
    }
}

app/JobDetail.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class JobDetail extends Model
{
    //
}

app/LeaveManagement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class LeaveManagement extends Model
{
    //
}

app/Module.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Module extends Model
{
    //

    protected $fillable = [
        'module_name', 'is_enabled','description'
    ];

    public function getSubModules(){
        return $this->hasMany('App\SubModule','module_id')->where('is_enabled',1);
    }

    public function getModules(){
        return $this::all();
    }
}

app/Overtime.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Overtime extends Model
{
    //
}

app/Position.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Position extends Model
{
    //
}

app/SubModule.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SubModule extends Model
{
    //
    protected $fillable = [
        'module_id', 'submodule_name','is_enabled','user_group','route'
    ];

    public function getModuleParent(){
        return $this->belongsTo('App\Module','module_id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/UserLevel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UserLevel extends Model
{
    //
}

resources/views/admin/overtime_management/include/categories.blade.php
<div class="right" style="float:right">
    <a class="btn btn-primary btn-icon icon-left" href="{{ route('job_detail.create') }}" id="">
        <i class="entypo-plus"></i>
        Add New
    </a>
</div>
<div class="row datatable-container" >
    <table class="table table-bordered datatable" id="table-OT-categories"  >
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>
@push('scripts')
    <script>
        $(document).ready(function (e) {
            let $table = $('#table-OT-categories');
            $table.DataTable({
                "aLengthMenu": [[20, 25, 50, -1], [10, 25, 50, "All"]],
                "bStateSave": true
            });
            // $table.closest( '.dataTables_wrapper' ).find( 'select' ).select2( {
            //     minimumResultsForSearch: -1
            // });
        })
    </script>
@endpush

resources/views/admin/overtime_management/include/requests.blade.php
<div class="right" style="float:right">
    <a class="btn btn-primary btn-icon icon-left" href="{{ route('job_detail.create') }}" id="">
        <i class="entypo-plus"></i>
        Add New
    </a>
</div>
<div class="row datatable-container" >
    <table class="table table-bordered datatable" id="table-OT-requests"  >
        <thead>
        <tr>
            <th>ID</th>
            <th>Employee</th>
            <th>Category</th>
            <th>Date filed</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>
@push('scripts')
    <script>
        $(document).ready(function (e) {
            let $table = $('#table-OT-requests');
            $table.DataTable({
                "aLengthMenu": [[20, 25, 50, -1], [10, 25, 50, "All"]],
                "bStateSave": true
            });
            // $table.closest( '.dataTables_wrapper' ).find( 'select' ).select2( {
            //     minimumResultsForSearch: -1
            // });
        })
    </script>
@endpush

resources/views/admin/overtime_management/index.blade.php
@extends('home')
@section('main-content')
    <ol class="breadcrumb">
        <li>
            <a href="#">
                <i class="entypo-folder"></i>
                Home
            </a>
        </li>
        <li><a href="#">Admin</a></li>
        <li class="active"><strong>Overtime Management</strong></li>
    </ol>
    <hr>

    <div class="row">
        <div class="col-md-12">
            <ul class="nav nav-tabs bordered">
                <li class="active">
                    <a href="#job_titles" data-toggle="tab" aria-expanded="true"> <span class="visible-xs"><i class="entypo-home"></i></span> <span class="hidden-xs">Overtime Categories</span> </a>
                </li>
                <li class="">
                    <a href="#employment_status" data-toggle="tab" aria-expanded="false"> <span class="visible-xs"><i class="entypo-user"></i></span> <span class="hidden-xs">Overtime Requests</span> </a>
                </li>
            </ul>

            <div class="tab-content">
                <div class="tab-pane active" id="job_titles">
                    @include('admin.overtime_management.include.categories')
                </div>

                <div class="tab-pane" id="employment_status">
                    @include('admin.overtime_management.include.requests')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <body class="page-body page-left-in">
        <div class="page-container">
            @include('layouts.sidebar')
            <div class="main-content">
                @include('layouts.topbar')
                @yield('main-content')
            </div>
        </div>
    </body>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/login.js') }}" ></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/login.css') }}" rel="stylesheet">
</head>
    @yield('content')
    <script src="{{ asset('js/fileinput.js') }}" defer></script>
    <script src="{{ asset('js/hrms.js') }}"></script>
    @stack('scripts')
</html>

resources/views/layouts/sidebar.blade.php
<div class="sidebar-menu">

    <div class="sidebar-menu-inner">

        <header class="logo-env">

            <!-- logo -->
            <div class="logo">
                <a href="index.html">
                    <img src="assets/images/logo@2x.png" width="120" alt="" />
                </a>
            </div>

            <!-- logo collapse icon -->
            <div class="sidebar-collapse">
                <a href="#" class="sidebar-collapse-icon"><!-- add class "with-animation" if you want sidebar to have animation during expanding/collapsing transition -->
                    <i class="entypo-menu"></i>
                </a>
            </div>


            <!-- open/close menu icon (do not remove if you want to enable menu on mobile devices) -->
            <div class="sidebar-mobile-menu visible-xs">
                <a href="#" class="with-animation"><!-- add class "with-animation" to support animation -->
                    <i class="entypo-menu"></i>
                </a>
            </div>

        </header>

        <div class="sidebar-user-info">

            <div class="sui-normal">
                <a href="#" class="user-link">
                    <img src="assets/images/thumb-1@2x.png" width="55" alt="" class="img-circle" />

                    <span>Welcome,</span>
                    <strong>Art Ramadani</strong>
                </a>
            </div>

            <div class="sui-hover inline-links animate-in"><!-- You can remove "inline-links" class to make links appear vertically, class "animate-in" will make A elements animateable when click on user profile -->
                <a href="#">
                    <i class="entypo-pencil"></i>
                    New Page
                </a>

                <a href="mailbox.html">
                    <i class="entypo-mail"></i>
                    Inbox
                </a>

                <a href="extra-lockscreen.html">
                    <i class="entypo-lock"></i>
                    Log Off
                </a>

                <span class="close-sui-popup">&times;</span><!-- this is mandatory -->				</div>
        </div>


        <ul id="main-menu" class="main-menu">
            <!-- add class "multiple-expanded" to allow multiple submenus to open -->
            <!-- class "auto-inherit-active-class" will automatically add "active" class for parent elements who are marked already with class "active" -->

            @foreach($globalModules->getModules() as $module)
                <li class="has-sub">
                    <a href="#">
                        <i class="{{ $module->icon }}"></i>
                        <span class="title">{{ $module->module_name }}</span>
                    </a>
                    <ul>
                        @foreach($module->getSubModules as $sub_module)
                            <li>
                                <a href="{!! $sub_module->route !!}">
                                    <span class="title">{{ $sub_module->submodule_name }}</span>
                                </a>
                            </li>
                        @endforeach
                    </ul>
                </li>
            @endforeach
            {{--<li>--}}
                {{--<a href="{{ route('home') }}" target="_blank">--}}
                    {{--<i class="entypo-gauge"></i>--}}
                    {{--<span class="title">Dashboard</span>--}}
                {{--</a>--}}
            {{--</li>--}}
            {{--<li class="has-sub">--}}
                {{--<a href="ui-panels.html">--}}
                    {{--<i class="entypo-users"></i>--}}
                    {{--<span class="title">Employees</span>--}}
                {{--</a>--}}
                {{--<ul>--}}
                    {{--<li>--}}
                        {{--<a href="{{ route('employees.index') }}">--}}
                            {{--<span class="title">Employee List</span>--}}
                        {{--</a>--}}
                    {{--</li>--}}
                    {{--<li>--}}
                        {{--<a href="{{ route('employees.create') }}">--}}
                            {{--<span class="title">Add Employee</span>--}}
                        {{--</a>--}}
                    {{--</li>--}}
                {{--</ul>--}}
            {{--</li>--}}
        </ul>

    </div>

</div>