routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Auth::routes();
//Route::resource('login','LoginController');
Route::middleware(['auth'])->group(function (){
    Route::resource('sub_module','SubModuleController');
    Route::get('generate/route','HomeController@generateRoute')->name('generate.route');
    Route::resource('company_structure','CompanyStructureController');
    Route::resource('job_detail','JobDetailController');
    Route::resource('overtime_management','OvertimeController');
    Route::resource('leave_management','LeaveManagementController');
    Route::resource('attendance','AttendanceController');
    Route::resource('users','UserController');
});
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/employees','EmployeeController');

app/Attendance.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Attendance extends Model
{
    //
}

app/CompanyStructure.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CompanyStructure extends Model
{
    //
    protected $fillable = [
        'name', 'description', 'address', 'type_id', 'parent_id'
    ];

    public function getTypeIdParent(){
        return $this->belongsTo('App\CompanyStructureType','type_id');
    }

    public function getParent(){
        return $this->belongsTo('App\CompanyStructure','parent_id');
    }

    public function getChildren(){
        return $this->hasMany('App\CompanyStructure','parent_id');
    }
}

app/CompanyStructureType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CompanyStructureType extends Model
{
    //
}

app/Department.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    //
    protected $fillable = [
        'department_name', 'department_motto', 'is_enabled',
    ];
}

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    //
}

app/EmployeeContact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EmployeeContact extends Model
{
    //
}

app/EmployeeEducation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EmployeeEducation extends Model
{
    //
}

app/EmployeeJobDescription.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EmployeeJobDescription extends Model
{
    //
}

app/EmployeeSocialMedia.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EmployeeSocialMedia extends Model
{
    //
}

app/EmployeeStatus.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EmployeeStatus extends Model
{
    //
}

app/EmployeeWorkExperience.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EmployeeWorkExperience extends Model
{
    //
}

app/GlobalModule.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;

class GlobalModule extends Model
{
    //
    protected $modules;
    protected $keyValuePair;

    public function __construct(Collection $modules)
    {
        $this->modules = $modules;
        foreach ($modules as $module){
            $this->keyValuePair[$module->key] = $module->value;
        }
    }

    public function has(string $key){ /* check key exists */ }
    public function contains(string $key){ /* check value exists */ }
    public function getModules(){
        return $this->modules;
    }
    public function get(string $key){
        return $this->modules[$key];
        /* get by key */
    }
}

app/JobDetail.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class JobDetail extends Model
{
    //
}

app/LeaveManagement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class LeaveManagement extends Model
{
    //
}

app/Module.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Module extends Model
{
    //

    protected $fillable = [
        'module_name', 'is_enabled','description'
    ];

    public function getSubModules(){
        return $this->hasMany('App\SubModule','module_id')->where('is_enabled',1);
    }

    public function getModules(){
        return $this::all();
    }
}

app/Overtime.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Overtime extends Model
{
    //
}

app/Position.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Position extends Model
{
    //
}

app/SubModule.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SubModule extends Model
{
    //
    protected $fillable = [
        'module_id', 'submodule_name','is_enabled','user_group','route'
    ];

    public function getModuleParent(){
        return $this->belongsTo('App\Module','module_id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/UserLevel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UserLevel extends Model
{
    //
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ModuleController.php
<?php

namespace App\Http\Controllers;

use App\Module;
use Illuminate\Http\Request;

class ModuleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Module  $module
     * @return \Illuminate\Http\Response
     */
    public function show(Module $module)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Module  $module
     * @return \Illuminate\Http\Response
     */
    public function edit(Module $module)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Module  $module
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Module $module)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Module  $module
     * @return \Illuminate\Http\Response
     */
    public function destroy(Module $module)
    {
        //
    }
}

resources/views/settings/modules/edit.blade.php
<form id="edit_submodule" action="{{ route('sub_module.update',$sub_module->id) }}" method="PUT" role="form" class="form-horizontal validate" >
        @csrf
        <div class="form-group">
        <label for="submodule_name" class="col-sm-3 control-label">Sub Module Name</label>

        <div class="col-sm-5">
            <input type="text" class="form-control" id="submodule_name" name="submodule_name"  placeholder="" value="{{ $sub_module->submodule_name }}"/>
        </div>
    </div>
    <div class="form-group">
        <label for="status" class="col-sm-3 control-label">Status</label>
        <div class="col-sm-5">
            <select name="status" id="status" class="form-control">
                <option value="1" {{ ($sub_module->is_enabled == 1 ? "selected" : "") }}>Enabled</option>
                <option value="2" {{ ($sub_module->is_enabled == 2 ? "selected" : "") }}>Disabled</option>
            </select>
        </div>
    </div>
    <div class="form-group">
        <label for="module_id" class="col-sm-3 control-label">Parent Module</label>
        <div class="col-sm-5">
            <select name="module_id" id="module_id" class="form-control">
                @foreach($modules as $module)
                    <option value="{{ $module->id }}" {{ ($module->id == $sub_module->module_id ? "selected":"") }}>{{ $module->module_name }}</option>
                @endforeach
            </select>
        </div>
    </div>
    <div class="form-group">
        <label for="route_generator" class="col-sm-3 control-label">Generate Route</label>
        <div class="col-sm-5">
            <div class="input-group">
                <input type="text" class="form-control" id="route_generator">

                <span class="input-group-btn">
											<button class="btn btn-primary btn_route_generate" type="button" data-url="{{ route('generate.route') }}">Go!</button>
										</span>
            </div>
        </div>


    </div>
    <div class="form-group">
        <label for="route" class="col-sm-3 control-label">Route</label>
        <div class="col-sm-5">
            <input type="text" name="route" id="route" class="form-control" value="{{ $sub_module->route }}" readonly>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-6">
            <button type="button" class="btn btn-default btn-icon icon-left cancel_button">
                Cancel
                <i class="entypo-cancel"></i>
            </button>
            <button type="submit" class="btn btn-blue btn-icon icon-left button-submit">
                Save
                <i class=""><span class="entypo-check"></span></i>
            </button>
        </div>
    </div>
</form>
<script>
    let rules = {
        sample_id : {
            required: true
        },
        submodule_name: {
            required: true
        }
    };
    neonLogin.validateForm('#edit_submodule',rules);
</script>

resources/views/settings/modules/index.blade.php
@extends('home')
@section('main-content')
    <ol class="breadcrumb">
        <li>
            <a href="#">
                <i class="entypo-folder"></i>
                Home
            </a>
        </li>
        <li><a href="#">System</a></li>
        <li class="active"><strong>Manage Modules</strong></li>
    </ol>
    <hr>
    <div class="row datatable-container" >
        <table class="table table-bordered datatable" id="table-permissions"  >
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th data-hide="phone">Parent Module</th>
                <th>Group</th>
                <th data-hide="phone,tablet">Status</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach($sub_modules as $sub_module)
                <tr>
                    <td>{{ $sub_module->id }}</td>
                    <td>{{ $sub_module->submodule_name }}</td>
                    <td>{{ $sub_module->getModuleParent->module_name }}</td>
                    <td>{{ ($sub_module->group == 1 ? "admin":"user") }}</td>
                    <td>{{ ($sub_module->is_enabled == 1 ? "Enabled" : "Disabled") }}</td>
                    <td class="cent">
                        <a href="#" class="btn btn-default btn-sm btn-icon icon-left edit_button" data-url="{{ route('sub_module.edit',$sub_module->id) }}">
                            <i class="entypo-pencil"></i>
                            Edit
                        </a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-primary panel_form " style="display: none;">
                <div class="panel-heading">
                    <div class="panel-title">Title</div>
                </div>
                <div class="panel-body">

                </div>
            </div>
        </div>
    </div>
@endsection
@push('scripts')
    <script>
        $(document).ready(function (e) {
            let $table = $('#table-permissions');
            $table.DataTable({
                "aLengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                "bStateSave": true
            });
            // $table.closest( '.dataTables_wrapper' ).find( 'select' ).select2( {
            //     minimumResultsForSearch: -1
            // });
        })
    </script>
@endpush